create table "public"."dishes" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" character varying not null,
    "price" numeric default '0'::numeric
);


alter table "public"."dishes" enable row level security;

CREATE UNIQUE INDEX dishes_name_key ON public.dishes USING btree (name);

CREATE UNIQUE INDEX dishes_pkey ON public.dishes USING btree (id);

alter table "public"."dishes" add constraint "dishes_pkey" PRIMARY KEY using index "dishes_pkey";

alter table "public"."dishes" add constraint "dishes_name_key" UNIQUE using index "dishes_name_key";


